# Generated by Django 6.0.2 on 2026-02-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
